### ISSUE TITLE
Certain maps do not display the correct station or z levels

### ISSUE THREAD

**Issue by Chatter42** [Eclipse-Station/Eclipse-Station-13#139]
#### Brief description of the issue
Consoles such as the power monitor or crew monitor incorrectly display the first three z-levels of the Tether instead of the NLS Southern Cross. This can be disorienting at best for anyone trying to find their way around or pinpoint the location of an injured crewmember.

#### What you expected to happen
To open up a monitor and be able to tell what I'm looking at

#### What actually happened
Get the map for an entirely different station instead

#### Steps to reproduce
- (Step 1) Use power monitor or crew monitor for literally any reason
- (Step 2) Observe as you are looking at the wrong map

#### Code Revision
Server revision: master - 2018-12-13
142bdd50ab91872967d65aedbeb91365a5687ea4 
 
#### Anything else you may wish to add:
![2019-02-04_10-40-45](https://user-images.githubusercontent.com/32618785/52222560-64d70100-2869-11e9-979f-870e64555c30.png)

**Comment by EvilJackCarver** [comment]
This issue is fixed by #187 (which, sadly, is not live yet)

**Comment by EvilJackCarver** [comment]
Closing, as the fix is long since live.
