### ISSUE TITLE
Mapping oversights- Missing items from the code

### ISSUE THREAD

**Issue by ArbyTheDragon** [Eclipse-Station/Eclipse-Station-13#186]
#### Brief description of the issue
Certain things are missing from the Northern Star map that the code we're on uses. Certain items like biomass for the cloning machine, the Sleeve-Mate, and the body design console disk.

#### What you expected to happen
The map to be adapted to the codebase.

#### What actually happened
Some key items from the codebase are missing from the map still.

#### Steps to reproduce
- (Step 1) Look around and think for a moment.
- (Step 2) Notice that some key items are missing.

#### Code Revision
master - 2019-04-03
- 78d1e112dd333d9a8fce745885919daa939575bb
 
#### Anything else you may wish to add:

-Station medbay cloning room traditionally had a couple bottles of 'Biomass'. It currently does not have this. Biomass can still be made in chemistry.
-There are no Sleeve-Mates in the station medbay. This was an alternative to the backup implanter. I believe there was typically one in cloning, one in medbay equipment, and one in secondary storage.
-Cloning room at the central command z-level has meat instead of biomass. Meat doesn't work on this codebase anymore. Since this cloning room doesn't start with any biomass, it can't be used unless some is produced from the nearby chemistry room.
-The 'body design console' was placed in the lobby of medbay, but there are no disks for it. As such, no bodies can be produced with it. It uses a special 'body design disk' that cannot be produced by science or ordered by cargo. There was traditionally a box of these disks behind the front desk in medbay.

**Comment by Chatter42** [comment]
Do you mean Southern Cross? Northern Star is where the shuttle goes after the crew transfer. I'm assuming that's what you mean but I just want to be certain.

**Comment by pantherpusher** [comment]
Yes he means Southern Cross

**Comment by EvilJackCarver** [comment]
After I get the new hardware fitted in my computer tomorrow or Tuesday,
I'll get on the horn with a medic main and look into getting it taken care
of, along with the access issues in the other tickets.

---
~ G. A. WILMBROKE

On mobile; typos are my own.

**Comment by Chatter42** [comment]
I wouldn't mind firing up dream maker and making edits to the map myself to fix it, but I might wait until there's more information about what could be added to fix that kind of stuff before submitting a PR for it
