### ISSUE TITLE
Crew transfer shuttle thinks it's a tram.

### ISSUE THREAD

**Issue by SectoidDan** [Eclipse-Station/Eclipse-Station-13#191]
#### Brief description of the issue
When the round ends with crew transfer, the Facility PA announces a transfer shuttle is on the way. However, there are two additional lines that are generated at the same time which incorrectly refer to the shuttle as a tram. One is from Southern Cross Space Control and one is from the NT Automated Tram itself. 

These messages also say the "tram" is departing from Southern Cross to Northern Star at a time when, presumably, the shuttle is actually going in the opposite direction to reach the station for boarding.

#### What you expected to happen
The automated systems to not refer to a shuttle as a tram, and to get the order of operations right. Perhaps request permission for a round-trip?

#### What actually happened
It calls the thing a tram and requests permission to leave SC before it has even arrived there.

#### Steps to reproduce
- join a round
- wait for it to end normally or via crew transfer vote
- listen to the announcements

#### Code Revision
78d1e112dd333d9a8fce745885919daa939575bb
 
#### Anything else you may wish to add:
![announcements](https://puu.sh/DcARz/032996daeb.png)

**Comment by EvilJackCarver** [comment]
[/code/modules/busy_space/air_traffic.dm:45](https://github.com/Eclipse-Station/Eclipse-Station-13/blob/master/code/modules/busy_space/air_traffic.dm#L45)

Simple enough to fix, if no-one else catches it I'll throw the local repo on a new branch and get started on it tomorrow morning.
