### ISSUE TITLE
Shuttles between station and surface take too long.

### ISSUE THREAD

**Issue by SectoidDan** [Eclipse-Station/Eclipse-Station-13#192]
#### Brief description of the issue
There are two shuttles that by default fly on autopilot between the station and the outpost on the surface. They spend two minutes docked at either end. However, the actual trip itself takes a long time to happen. The shuttle makes five jumps: first the undocking, which is thankfully instant apart from the spool-up time. Then it spools up again for a minute-long journey, stops, and immediately spools up a third time for yet another minute-long journey. Lastly there's a thirty-second stint through the atmosphere before landing immediately.

The second transit through space is unnecessary and both are needlessly long. Cutting one and shortening the other to 30s like the atmosphere flight makes getting up or down less painful. Note also that these shuttles are the only way for regular crew to move between the station and the outpost; the teleporters are locked behind command-level access and r-walls.

Finally, these are the only two pilotable shuttles on the station, and share double-duty with regular transit and explorer stuff. Adding a third shuttle to (currently empty) hanger 3 specifically for the pilot and explorer team avoids situations where regular crew can get stranded on the surface (as has happened to me).

#### What you expected to happen
Shuttles moving between station and outpost regularly and relatively quickly.

#### What actually happened
They take forever and stop several times along the way, if they're not taken by explorers.

#### Steps to reproduce
- (Step 1) Try to get from the station to the outpost or vice versa via shuttle.
- (Step 2) Die of old age, or at least have enough time to go make a cup of tea or a sandwich or something.
- (Step 2.5) Alternatively, never go anywhere because one shuttle is in the wilderness and the other is locked at the outpost.

#### Code Revision
78d1e112dd333d9a8fce745885919daa939575bb
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

**Comment by EvilJackCarver** [comment]
I wouldn't know where to begin my codebase search for the relevant things to correct.

If you have a Pilot character and can take control of a ship, it'd be appreciated it you could get me a list of the possible destinations; that'd be a bit easier for me to search.

**Comment by Chatter42** [comment]
@EvilJackCarver I remembered "Skies of Sif" as a possible destination when piloting as one of my own characters a few times, and that brought me to [crew_shuttles.dm](https://github.com/Eclipse-Station/Eclipse-Station-13/blob/f38eebb11c409311fd6cca7944f6bb3bda20aeeb/maps/southern_cross/shuttles/crew_shuttles.dm).

**Comment by EvilJackCarver** [comment]
The AEIOU Edits will be strong with that file, then. Nothing I can't fix. 

Do we really want all those notifications, though?

**Comment by Chatter42** [comment]
On the one hand, being able to discern the most recent landing location of those shuttles can be kind of important, but the notifications would get annoying. I'm honestly not sure how to go about addressing that.

I think there are supposed to be consoles that let you call the shuttle back to a dock, but they're either broken or just aren't functional in the current iteration of this map. There are even 'control rooms' right next to the hangars that don't seem to serve any real function.

**Comment by EvilJackCarver** [comment]
That's gonna be one of those 'tear apart the map' things, then, which in and of itself is going to be a pain in the ass if I don't go to an ancient part of the codebase pre-dating the move to the SCross.

I'm looking into taking a leg out of the shuttles' paths since the code to allow you to visit various planets at "some stage" never was implemented; that'd save a minute and make the shuttles' round-trip about 90 seconds plus spool-up and dock times rather than 2'30". It'd also slow notifications down a bit, too, actually (due to the 2 minute leave delay).

I'll have to make some *extensive* edits to the code, though. Best bet would probably be to move it to a modular folder and do things that way.

**Comment by cruxxansata** [comment]
I'll save you some trouble and let you guys know Nestor's planning to code a two-way teleporter for getting between the surface and the station, with the idea of making shuttles into a back-up means of transport.

**Comment by cruxxansata** [comment]
I do think it could be made shorter either way, though. I think we could all appreciate what you're offering to do, @EvilJackCarver

**Comment by EvilJackCarver** [comment]
If you've got a source for that, I'd love to see it. 

Otherwise, the way I'm looking to go about it is cut the Sif Orbit leg of the journey out completely and make it a 60-second space ride, plus the 30 seconds in re-entry. Give or take. I'm looking at the code and the current flight says it's 75 seconds (1'15") but another part of it mentions it takes 2 and a half minutes to arrive.

`autopilot_first_delay = 380 // Twelve and a half minutes at roundstart. Two minutes otherwise. This should leave when the first shuttle arrives at the outpost.
`

I'll take a photo of my whiteboard and edit it in here, in a second.

**Comment by cruxxansata** [comment]
That looks good to me, honestly. I appreciate that you're not just making some values smaller, you're cutting out redundant portions of the journey that artificially lengthen it.

**Comment by Chatter42** [comment]
Two-way teleporter notwithstanding, a quality of life change like this one in-between now and whenever that is added is better for sanity's sake. I also like how this looks. It will make misclicking a lot less painful and tedious when you inevitably have a brainfart and choose the wrong destination while manually piloting..

**Comment by SectoidDan** [comment]
Works for me. Will you just turn off the radio announcements to reduce spam, or change it to a local announcement in the hangers, or adding it to communicators like the weather, or... ? I appreciate doing anything except just turning it off is probably significantly more work, though.

If Nestor adds a simple two-way teleporter as well that'd be great too.

**Comment by EvilJackCarver** [comment]
I'll continue to try to find ways to counter the long shuttle times, but at the moment the melatonin's kicking in hard. 

Another thing I could do is try to see if I can move the gateway teleporter out of the gateway itself and move it on the station; there's three or four unused construction areas on SC1F. Could repurpose one of the rooms as a spawn room, similar to the one on the Tether by Medical.

A third option would be the two-way teleporter system Chats mentioned; I'd have to look into teleporter code to see if there's a way to make teleporter A only go to beacon B, and teleporter B only go to beacon A, for example. There's a couple of utility rooms on the Southern Cross that I could use for that (or I could repurpose the garage, but that's a bit large for just a couple of teleporters).

A fourth option would be SPESS ELEVATOR 2 ELECTRIC BOOGALOO which I am not doing and you could not _pay_ me to do.

---

Radio announcements can be turned off completely, but at this stage, not localised. I could do something similar to the emergency channel thing I did that got rejected and throw ATC traffic on its own channel, but that's a bit of a project and I'd prefer to do that separately; notification spam is not the point of this ticket, shuttle time is.

**I should make it clear that all of this is stuff on the back burner for the time being.** I need some time to cool off between mapping/coding before I burn myself out again.

**Comment by cruxxansata** [comment]
What if we moved shuttle RC announcements to its own frequency, so you had to opt in to listen to it?

**Comment by EvilJackCarver** [comment]
>What if we moved shuttle RC announcements to its own frequency, so you had to opt in to listen to it?

See previous response:

> I could do something similar to the emergency channel thing I did that got rejected and throw ATC traffic on its own channel
