### ISSUE TITLE
Using supply console in cargo gives an option to order a "null - null"

### ISSUE THREAD

**Issue by pandacat13** [Eclipse-Station/Eclipse-Station-13#200]
#### Brief description of the issue
Using the supply console inside cargo has a "null - null" option under the Voidsuit category.

#### What you expected to happen
Not to see a "null - null" option.

#### What actually happened
"null - null" shows up in the list of items to request

#### Steps to reproduce
- (Step 1) Open the supply console and open the Voidsuit category.

#### Code Revision
275360a9898be61dcba0c45b8b630672a6d7d9e4 
 
#### Anything else you may wish to add:
![image](https://user-images.githubusercontent.com/49799706/56449284-3a7fd600-62e5-11e9-9b63-5047d1d86f8c.png)

**Comment by EvilJackCarver** [comment]
Can you do me a favour, look through the categories and tell me if there's any other oddities like that in them? If there are, I'd like to get them all knocked out at once.

**Comment by pandacat13** [comment]
Done and done. No other weird/broken crates.
