### ISSUE TITLE
Resleeving setup is gone. Cloning setup in its place.

### ISSUE THREAD

**Issue by cruxxansata** [Eclipse-Station/Eclipse-Station-13#271]
#### Brief description of the issue
The mapmerge got rid of the resleeving machines in the medbay and replaced them with cloning machines.

#### Additional info:
Server revision: 384de516f25d02ed82451652

**Comment by EvilJackCarver** [comment]
Caused by #256 

Another one of my fuck-ups to fix, Nestor...
