### ISSUE TITLE
The slimes are missing from xenobiology??

### ISSUE THREAD

**Issue by cruxxansata** [Eclipse-Station/Eclipse-Station-13#273]
#### Brief description of the issue
The slimes are gone. They aren't there. The grey slimes in the station's xenobiology pens aren't there at round-start and there aren't any slime cores either. They aren't in sample storage, either.

#### What you expected to happen
To be able to do xenobiology.

#### What actually happened
I can't do xenobiology. There are no grey slimes, which are necessary to do your job at all.

#### Steps to reproduce
Start round, notice no slimes? They aren't on the surface outpost either, which should at least have cores in its pens.

#### Additional info:
Server revision: 384de516f25d02ed82451652

![image](https://user-images.githubusercontent.com/13389337/68176774-be30a580-ff4b-11e9-813d-ee231bd1a531.png)

**Comment by drexample** [comment]
I gave you promethean blobs, is that not enough?

**Comment by EvilJackCarver** [comment]
Looks to be fixed from #269
